name: Build and Deploy to Nexus

on:
  push:
    branches:
      - master   # or your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: nexus
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
        run: |
          mvn deploy \
            -DaltDeploymentRepository=nexus::default::${NEXUS_URL} \
            -Dnexus.username=${NEXUS_USERNAME} \
            -Dnexus.password=${NEXUS_PASSWORD}
